version: '3.8'

volumes:
  postgres_volume:

services:
  pg:
    image: postgres:16.2-alpine3.19
    environment:
      - "POSTGRES_DB=${PG_DB_NAME}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    ports:
        - "${PG_PORT}:5432"
    volumes:
        - postgres_volume:/var/lib/postgresql/data

  migrator:
    build:
      context: .
      dockerfile: migration.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: pg

  chat-service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      DB_HOST: pg
#    env_file:
#      - .env
    ports:
      - "50552:50552"